### PR TITLE
added subtitle conversion to decyptor

### PR DESCRIPTION
**Pull request by mdomnita**
I added my captiontosrt code for the windows version. Even if the conversion is quite basic and still needs work, the subtitle filename, renaming of files and conversion along with the other videos works fine.
Only tested on Windows 10, Visual Studio 15.

### CODE REVIEW

**Comment by mdomnita** [comment]
Hello @bittaurus . Someone updated and corrected a few things in my fork of the CaptionToSrtConvertor. I will check it out, maybe compile it and send a link. 
I will also make a new pull request to @h4ck-rOOt  if it works fine.

**Comment by Dev-iL** [comment]
@mdomnita I can submit a PR as I already have this integrated. Perhaps also upload the binaries... I think your repo should be a submodule of this one, but I have no experience with that sort of things.

**Comment by mdomnita** [comment]
Hey @Dev-iL . My repo was a separate project I did for myself that worked along with this one to solve #9 . I then submitted a pull request to integrate it in the initial project. You can also submit a PR if you have a fork with this integrated or if you made the changes directly on a clone of this repo. If you manage to do it, thanks. If not, I will take some time over the weekend to get a Lynda demo account and test it on some courses then make a PR.

**Comment by rosetinted** [comment]
@bittaurus @Dev-iL @mdomnita 

I came up with a solution for the subtitle problem. Looking good so far with the 16 courses I tested it on. I've submitted a pull request for mdomnita's [repository](https://github.com/mdomnita/Lynda-Decryptor), but while that's pending the code is available on my own [fork](https://github.com/rosetinted/Lynda-Decryptor). I've also uploaded a [binary](https://github.com/rosetinted/Lynda-Decryptor/releases/tag/v1.4). Let me know if you find any flaws.

**Comment by Dev-iL** [comment]
@rosetinted just wondering.. Did you compare this to the current output of https://github.com/mdomnita/LyndaCaptionToSrtConvertor ? Does your code perform better?

**Comment by rosetinted** [comment]
@Dev-iL 

I haven't compared it, I just learned about it now. My solution replaces the regex filter with an extraction based on location, avoiding any binary data. That should make it immune against edge-cases where binary characters look like part of the subtitle but aren't actually.

The regex code was a little too complicated for me to assess if your fixes to [LyndaCaptionToSrtConvertor](https://github.com/mdomnita/LyndaCaptionToSrtConvertor) cover all possible problems with character filtering, but in that regard my solution seems more robust. No problems turned up during my testing, so if your code is good they should perform at least equally well.

**Comment by Dev-iL** [comment]
@rosetinted Looks like your solution is indeed more robust. Good job!

**Comment by hopa102** [comment]
where can I download the last version of this file ? " exe. file "

**Comment by rosetinted** [comment]
@hopa102 You can find an executable [here](https://github.com/rosetinted/Lynda-Decryptor/releases).

**Comment by hopa102** [comment]
@rosetinted Thanks , but I'm look for LyndaCaptionToSrtConvertor "exe. file"

**Comment by rosetinted** [comment]
@hopa102 I don't have a build for that right now, but the Lynda-Decryptor exe that I linked will also convert the subtitles.

**Comment by Karambeigi** [comment]
Dear my friend,
Many thanks for your great program.
It works properly, particularly in the case of subtitle conversion.
Kind regards,

**Pull request merged**
